name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🌟 ハイライト'
    labels:
      - 'highlights'
      - 'feature'
  - title: '💥 破壊的変更'
    labels:
      - 'breaking change'
  - title: '🏗️ 改善・強化'
    labels:
      - 'enhancement'
  - title: '📈 バグ修正'
    collapse-after: 5
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 メンテナンス'
    collapse-after: 5
    
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # #と@を追加して言及を無効にし、`を追加してコードブロックを無効にすることができる。
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 変更履歴

  $CHANGES
