// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaumiDiscord.Core.Server.DataContext;

#nullable disable

namespace RaumiDiscord.Core.Server.Migrations
{
    [DbContext(typeof(DeltaRaumiDbContext))]
    [Migration("20250117001524_DiscordComponentModel")]
    partial class DiscordComponentModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RaumiDiscord.Core.Server.Models.DiscordComponentModel", b =>
                {
                    b.Property<Guid>("CustomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaRaumiComponentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomId");

                    b.ToTable("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
