name: DeltaRaumiCompileTest

# 実行条件
on:
  pull_request:

# ジョブの中身
jobs:
  # ひとかたまりのジョブを定義(別のジョブになると環境も立て直しになる)
  Job1:
    # 実行する環境を指定
    runs-on: ubuntu-20.04
    # ジョブの中で実行する処理をステップで定義
    steps:
    
      - uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      
      - name: DotNet Build Restore
        run: |
          dotnet build --no-restore /warnaserror -clp:NoSummary
        
      
  
