name: Release (master)
on:
  push:
    # オプション。デフォルトはすべて。
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    permissions:
      # githubリリースを作成するには、書き込み権限が必要です。
      contents: write
      # オートラベリングには書き込みパーミッションが必要です。
      # そうでない場合は、少なくとも読み込みパーミッションが必要
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4.2.2
      - name: generate a release note and a version tag
        uses: release-drafter/release-drafter@v6.0.0
        with:
          tag: v${{ inputs.release_version }}
          publish: false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      
