name: Release Drafter

on:
  push:
    # オプション。デフォルトはすべて。
    branches:
      - main
      - master

  # pull_requestイベントはオートラベリングにのみ必要です。
  pull_request:
    # アクションが扱うのは以下のタイプだけですが、デフォルトですべてにすることもできます。
    types: [opened, reopened, synchronize]
  # pull_request_targetイベントは、autolabelerがフォークからのPRをサポートするために必要です。
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  update_release_draft:
    permissions:
      # githubリリースを作成するには、書き込み権限が必要です。
      contents: write
      # オートラベラーには書き込み許可が必要
      # そうでない場合は、少なくとも
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # (オプション) GitHub Enterprise では GHE_HOST 変数の設定が必要です。
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # プルリクエストが "master "にマージされる際に、次のリリースノートを作成します。
      - uses: release-drafter/release-drafter@v6
        # (オプション) .github/ からの相対パスで、使用する設定名を指定します。デフォルト: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
